name: Publish
on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
    branches:
      - main
jobs:
  publish:
    # 只在 CI workflow 成功时执行
    if: github.event.workflow_run.conclusion == 'success'
    name: Publish to NPM
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Check for tag
        id: check_tag
        run: |
          git fetch --tags
          LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
          if [ ! -z "$LATEST_TAG" ]; then
            echo "tag=$LATEST_TAG" >> $GITHUB_OUTPUT
            echo "has_tag=true" >> $GITHUB_OUTPUT
          else
            echo "has_tag=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Use Node.js
        if: steps.check_tag.outputs.has_tag == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Publish to NPM
        if: steps.check_tag.outputs.has_tag == 'true'
        run: |
          echo "Publishing version $(node -p "require('./package.json').version")"
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
