name: Publish
on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
    branches:
      - main
jobs:
  publish:
    # 只在 CI workflow 成功且有 tag 推送时执行
    if: github.event.workflow_run.conclusion == 'success' && startsWith(github.ref, 'refs/tags/')
    name: Publish to NPM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Publish to NPM
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
